### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by miyya0707** [guojiajeremy/Dinomaly#10]
Thanks for your awesome project! I’m interested in using the Real-IAD dataset for experiments and emailed a request a few days ago, but I haven’t received a response yet. Could you let me know if you experienced a long wait to access the dataset?

Thanks for your help!

**Comment by guojiajeremy** [comment]
I heard some other applicants experienced such long wait as well. It didn't took so long for me, maybe because I applied very earliy when there was not many request. 

Maybe try to email them again? Also, I email them by Gmail at first, but they replied to asked me to use institution email (school email). Maybe try institution email.

**Comment by miyya0707** [comment]
Thank you so much for your sharing! I will try sending the email again and patiently wait for a response.
